# Generated by Django 6.0.7 on 2026-08-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Beans", "Beans"),
                            ("Equipment", "Equipment"),
                            ("Merchandise", "Merchandise"),
                        ],
                        default="Beans",
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("description", models.TextField()),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Best Seller, New, Single Origin",
                        max_length=50,
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
