# Generated by Django 6.0.7 on 2026-08-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Barista Workshop", "Barista Workshop"),
                            ("Coffee Tasting", "Coffee Tasting"),
                            ("Private Event", "Private Event"),
                        ],
                        max_length=100,
                    ),
                ),
                ("date", models.DateField()),
                ("guests", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
