# Generated by Django 6.0.7 on 2026-08-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="preferred_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("routine", "Routine Maintenance"),
                    ("repair", "Emergency Repair"),
                    ("descale", "Descaling & Water Filtration"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
