# Generated by Django 6.0.7 on 2026-08-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_machine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.AddField(
            model_name="booking",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guests",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="booking",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="machine",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="machine",
            name="specs",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="badge",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
